// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-xZe6L7ZT_BzvB7pxuN0rwutrtL-eCf4',
    appId: '1:869402912009:web:c2dc2f796c7aae63ba9fd8',
    messagingSenderId: '869402912009',
    projectId: 'persanal--account',
    authDomain: 'persanal--account.firebaseapp.com',
    storageBucket: 'persanal--account.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcJeHqInQtBd3IXF4t9oS3X_4wiPBleNo',
    appId: '1:869402912009:android:ef46cfa1f84c546aba9fd8',
    messagingSenderId: '869402912009',
    projectId: 'persanal--account',
    storageBucket: 'persanal--account.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUfc2VNo7fRY_BaBFsNWZqlVg9iRNLXIw',
    appId: '1:869402912009:ios:e7f2f84ded788ec3ba9fd8',
    messagingSenderId: '869402912009',
    projectId: 'persanal--account',
    storageBucket: 'persanal--account.appspot.com',
    iosBundleId: 'com.example.persanalAccount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUfc2VNo7fRY_BaBFsNWZqlVg9iRNLXIw',
    appId: '1:869402912009:ios:414081f0606ac9f7ba9fd8',
    messagingSenderId: '869402912009',
    projectId: 'persanal--account',
    storageBucket: 'persanal--account.appspot.com',
    iosBundleId: 'com.example.persanalAccount.RunnerTests',
  );
}
